# 예외 처리

Nest는 프레임워크 내에 예외 레이어를 두고 있다. 애플리케이션을 통틀어 제대로 처리하지 못한 예외를 처리하는 역할을 한다. 여러분이 아무런 작업을 하지 않아도 기본 예외 처리기가 예외를 잡아서 유저가 이해하기 쉬운 형태로 변환하여 전송된다. 간단하게 예외를 일으켜서 어떤 에러가 발생하는지 확인해 보도록 하자.

```ts
import { InternalServerErrorException } from '@nestjs/common';

@Controller()
export class AppController {
    ...

  @Get('/error')
  error(foo: any): string {
    return foo.bar();
  }
}
```

foo가 undefined이기 때문에 아래와 같은 에러가 발생한다.

```ts
$ curl http://localhost:3000/error
{
    "statusCode":500,
    "message":"Internal Server Error"
}
```

Nest가 제공하는 예외에 대한 많은 클래스들이 있다. 위 결과를 보면 에러가 발생했을 때 응답을 JSON 형식으로 바꿔주고 있는데 이는 기본으로 내장된 전역 예외 필터가 처리한다. 내장 예외 필터는 인식할 수 없는 에러(HttpException도 아니고, HttpException를 상속받지도 않은 에러)를 InternalServerErrorException으로 변환해준다. MDN 문서에 따르면 500 InternalServerError는 "요청을 처리하는 과정에서 서버가 예상하지 못한 상황에 놓였다는 것을 나타낸다"고 되어 있다. InternalServerErrorException의 선언을 보면 HttpException을 상속받고 있고 HttpException은 다시 자바스크립트의 Error를 상속한다. 결국 모든 예외는 Error객체 로부터 파생된 것이다.

```ts
export declare class InternalServerErrorException extends HttpException {
    constructor(objectOrError?: string | object | any, description?: string);
}

export declare class HttpException extends Error {
...
}
```

그 외 Nest에서 제공하는 모든 예외 역시 HttpException을 상속하고 있다. 이 예외 클래스들을 이용하여 상황에 따라 적절한 예외를 발생시켜주자(throw). 적절한 예외처리는 API를 호출한 클라이언트에서 에러를 쉽게 이해하고 대처할 수 있도록 한다. 예를 들어 유저 정보를 가져오기 위해 /users/:id 엔드포인트로 조회를 하려고 하는데, 도메인 규칙상 id는 1보다 작을 수가 없다. 클라이언트가 id를 0과 같이 잘못된 값으로 전달한 경우는 400 Bad Request 를 응답으로 보낸다.

```ts
@Get(':id')
findOne(@Param('id') id: string) {
  if (+id < 1) {
    throw new BadRequestException('id는 0보다 큰 정수여야 합니다');
  }

  return this.usersService.findOne(+id);
}
```

```bash
$ curl http://localhost:3000/users/0 -v
...
< HTTP/1.1 400 Bad Request
...
{
    "statusCode":400,
    "message":"id는 0보다 큰 정수여야 합니다",
    "error":"Bad Request"
}
```

예외의 생성자에 전달할 메시지가 응답에 함께 출력되었다. HttpException 클래스를 다시 자세히 살펴보겠다.

```ts
export declare class HttpException extends Error {
        ...
    constructor(response: string | Record<string, any>, status: number);
        ...
}
```

생성자는 2개의 인자를 받고 있다.

- `response`: JSON 응답의 본문입니다. 문자열이나 Record 타입의 객체를 전달할 수 있습니다.
- `status`: 에러의 속성을 나타내는 HTTP 상태 코드입니다.

JSON 응답의 본문은 statusCode와 message 속성을 기본으로 가진다. 이 값은 위에서 예외를 만들때 생성자에 넣어준 response와 status로 구성된다.

미리 제공된 BadRequestException 대신 HttpException을 직접 전달한다면 다음과 같이 작성한다.

```ts
throw new HttpException(
  {
    errorMessage: 'id는 0보다 큰 정수여야 합니다',
    foo: 'bar'
  },
  HttpStatus.BAD_REQUEST
);

```

```ts
{
    "errorMessage":"id는 0보다 큰 정수여야 합니다",
    "foo":"bar"
}
```

다음은 Nest에서 제공하는 표준 예외들이다. 자주 쓰지 않는 것들도 포함되어 있지만 어떤 상황에서 어떤 에러를 내야 하는지 MDN문서를 꼭 한번 읽어 보도록 하자.

